#!/usr/bin/env bash
# Print domains and subdomains

print_domain_subdomain () {
    local full_domain=$1
    local subdomain=$2
    local ip=$(dig +short "$full_domain")
    
    if [ -z "$ip" ]; then
        echo "The subdomain $full_domain does not exist or has no A record."
    else
        echo "The subdomain $subdomain is an A record and points to $ip"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi

